

N <- array(data = NA, dim = c(nySpinFit, nage, ns))
R <- matrix(data = NA, nrow = nySpinFit, ncol = ns)
Run <- array(data = NA, dim = c(nySpinFit, nage, ns))
S <- array(data = NA, dim = c(nySpinFit, nage, ns))
Stot <- array(data = NA, dim = c(nySpinFit, ns))
Stot_oe <- array(data = NA, dim = c(nySpinFit, ns))
C <- array(data = NA, dim = c(nySpinFit, nage, ns))
Ctot <- array(data = NA, dim = c(nySpinFit, ns))
Ctot_oe <- array(data = NA, dim = c(nySpinFit, ns))
paa_oe <- array(data = NA, dim = c(nySpinFit, nage, ns))
run_oe <- array(data = NA, dim = c(nySpinFit, nage, ns))
R_oe <- matrix(data = NA, nrow = nySpinFit, ncol = ns)
Smsy <- numeric(nySpinFit)
